version: '3.8'

services:
  db:
    image: postgres:15
    container_name: magal_db_prod
    restart: always
    environment:
      POSTGRES_DB: magal_db
      POSTGRES_USER: magal_user
      POSTGRES_PASSWORD: changeme_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: morlayecisse1196/django-app:latest
    container_name: django_backend_prod
    restart: always
    env_file: .env
    depends_on:
      - db

  frontend:
    image: morlayecisse1196/react-frontend:latest
    container_name: react_frontend_prod
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
